// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; // ✅ FIX IMPORTANT
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIBj3b40LJidv2Tc6nEFSzUculsvKavA',
    appId: '1:523675964953:web:64df858985e214b292fc88',
    messagingSenderId: '523675964953',
    projectId: 'felicien-a543c674',
    authDomain: 'felicien-a543c674.firebaseapp.com',
    storageBucket: 'felicien-a543c674.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYaeyzwWAzx7mUXoCQlwnFQuR46m9bfg',
    appId: '1:523675964953:android:a77ef966ace654f692fc88',
    messagingSenderId: '523675964953',
    projectId: 'felicien-a543c674',
    storageBucket: 'felicien-a543c674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHsygfRKh4SA-3VBgvPvl8fSxXmbyIEe0',
    appId: '1:523675964953:ios:624e30a8cdc2672692fc88',
    messagingSenderId: '523675964953',
    projectId: 'felicien-a543c674',
    storageBucket: 'felicien-a543c674.firebasestorage.app',
    iosBundleId: 'com.example.smartbusudm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHsygfRKh4SA-3VBgvPvl8fSxXmbyIEe0',
    appId: '1:523675964953:ios:624e30a8cdc2672692fc88',
    messagingSenderId: '523675964953',
    projectId: 'felicien-a543c674',
    storageBucket: 'felicien-a543c674.firebasestorage.app',
    iosBundleId: 'com.example.smartbusudm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfIBj3b40LJidv2Tc6nEFSzUculsvKavA',
    appId: '1:523675964953:web:518d11f517dc4d1892fc88',
    messagingSenderId: '523675964953',
    projectId: 'felicien-a543c674',
    authDomain: 'felicien-a543c674.firebaseapp.com',
    storageBucket: 'felicien-a543c674.firebasestorage.app',
  );

  // ✅ Linux ajouté proprement (fallback web)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAfIBj3b40LJidv2Tc6nEFSzUculsvKavA',
    appId: '1:523675964953:web:64df858985e214b292fc88',
    messagingSenderId: '523675964953',
    projectId: 'felicien-a543c674',
    authDomain: 'felicien-a543c674.firebaseapp.com',
    storageBucket: 'felicien-a543c674.firebasestorage.app',
  );
}